---
# ansible-playbook -i inventory.ini facts-playbook.yml
# No necessita become
- name: Gather facts
  hosts: webservers
  gather_facts: true

  tasks:
  # name sempre comença per majúscula
  # FQCN prefereix ansible.builtin.app en comptes de apt
    - name: Display facts for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

    - name: Display specific system information
      ansible.builtin.debug:
        msg:
          - "Host: {{ ansible_hostname }}"
          - "IP Address: {{ ansible_default_ipv4.address }}"
          - "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"
