# ansible-playbook -i inventory.ini -K install-playbook.yml
# usuari isard contrasenya pirineus
- name: Instala paquets amb apt dpkg
  hosts: hosts
  become: true
  tasks:

    - name: Add GNS3 repository into sources list
      ansible.builtin.apt_repository:
        repo: ppa:gns3/ppa

    - name: Apt install
      ansible.builtin.apt:
        update_cache: true
        state: present
        pkg:
          - debconf-utils
          - gns3-gui
          - gns3-server
          - iperf3
          - libreoffice
          - mtr
          - putty
          - wireguard-tools
          - wireshark

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/isard/Packet_Tracer822_amd64_signed.deb
        dest: ./Packet_Tracer822_amd64_signed.deb
        owner: isard
        group: isard
        mode: '0644'

    - name: Debconf set selection for apt deb
      ansible.builtin.command: >
        echo PacketTracer   PacketTracer_822_amd64/show-eula note  | debconf-set-selections
        echo PacketTracer   PacketTracer_822_amd64/accept-eula boolean true | debconf-set-selections
      changed_when: true

    - name: Install packettracer deb file
      ansible.builtin.apt:
        state: present
        deb: /home/isard/Packet_Tracer822_amd64_signed.deb

# Problema amb el path d'aquesta collection
    # - name: Snap install
    #   community.general.snap:
    #     name:
    #       - firefox
    #       - postman
