---
- name: Echo playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Echo inventory_hostname
      ansible.builtin.debug:
        msg:
          - "Hello from Ansible playbook!"
          - "This is running on {{ inventory_hostname }}"
    - name: Echo hostvars
      ansible.builtin.debug:
        msg:
          - "This are hostvars {{ hostvars }}"
    - name: Echo play_hosts
      ansible.builtin.debug:
        msg:
          - "This ara play_hosts {{ play_hosts }}"
    - name: Echo groups
      ansible.builtin.debug:
        msg:
          - "This are groups {{ groups }}"
    - name: Echo group_names
      ansible.builtin.debug:
        msg:
          - "These are group_names {{ group_names }}"
